### ISSUE TITLE
Examples / Docs TODO

### ISSUE THREAD

**Issue by willtebbutt** [JuliaGaussianProcesses/AbstractGPs.jl#95]
@theogf pointed out [here](https://github.com/JuliaGaussianProcesses/AbstractGPs.jl/pull/93#issuecomment-756046955) that we've got some missing examples, and @devmotion pointed out that some consolidation / extension of our existing examples would be helpful. Moreover, we've known for a while that there's stuff that needs to be better documented (e.g. how to handle multi-dimensional inputs). It makes sense to tackle these in the same issue so that we have a vaguely joined up approach to our examples + docs.

Below is a very incomplete list, please feel free to extend below, and I'll add them to this list (or add them directly yourself if GH allows that... I have no idea whether it does or not).

- [ ] multi-input example
- [ ] multi-input docs (`ColVecs` vs `RowVecs` vs `Vector{<:AbstractVector}` etc)
- [ ] multi-output docs (using the multi-output abstractions in KernelFunctions)
- [ ] multi-output example (using the multi-output abstractions in KernelFunctions)
- [ ] sparse-approximation example -- the solution is very innaccurate, so possibly isn't the best showcase for sparse methods 😂 perhaps we could construct an example where the approximate posterior is less bad, but still imperfect?

**Comment by theogf** [comment]
Maybe as a (small) addition would be to create notebooks via Literate.jl and display them with nbviewer + having a notebook on binder. I think @devmotion did something similar for one of his package and I did the same for AGP.jl

**Comment by willtebbutt** [comment]
This sounds like a good idea. I guess this would be straightforward, since we've been writing our examples using Literate anyway, right?

**Comment by willtebbutt** [comment]
Another thing that we might consider doing is provide examples that use [ParameterHandling.jl](https://github.com/invenia/ParameterHandling.jl/) and `Functors.jl` interface.

**Comment by willtebbutt** [comment]
I've closed #30 because it went stale. @thomasgudjonwright volunteered to take a look at the general problem of docs for MOGP some time next month (hopefully). @sharanry if you get time to revive #30, please do -- we remain keen to improve the MOGP docs.
